source 'https://rubygems.org'

gem 'cuba'
gem 'pg'
gem 'thin'
gem 'rake'
gem 'rack-protection'
gem 'activerecord'
gem 'active_record_migrations'
gem 'geocoder'
gem 'devise'
gem 'oj'
gem 'oj_mimic_json'
gem 'rspec', '~> 2.99'
gem 'pry'
gem 'shoulda-matchers'
